#Datetime imports
from datetime import datetime, timezone
#App.auth imports
from app.auth.domain.entities import User
from app.auth.domain.ports import UserRepository
from app.auth.domain.errors import InvalidCredentialsError, UserAlreadyExistsError
#App.core imports
from app.core.security import verify_password, hash_password
from app.core.jwt import create_access_token

class AuthService:
    def __init__(self, user_repository: UserRepository):
        self.user_repository = user_repository

    async def register(self, email: str, password: str) -> User:
        email_norm = email.strip().lower()
        exists = await self.user_repository.get_by_email(email_norm)
        #Check if there is already a user with email entered by user
        if exists is not None:
            raise UserAlreadyExistsError("An account related to this email already exists.")
        #Build instance of User entity
        user = User (
            #No need to set ID as it will be generated by Mongo
            id="",
            email=email_norm,
            password_hash=hash_password(password),
            created_at=datetime.now(timezone.utc)
        )
        #Await to create user in persistence, awaited needed because of async implementation of motor (MongoDB)
        created = await self.user_repository.create(user)
        return created
    
    async def login(self, email: str, password: str) -> str:
        email_norm = email.strip().lower()

        user = await self.user_repository.get_by_email(email_norm)
        if user is None:
            #Avoid giving information about which part is incorrect as a security measure
            raise InvalidCredentialsError("Invalid email or password.")
        
        if not verify_password(password, user.password_hash):
            #Avoid giving information about which part is incorrect as a security measure
            raise InvalidCredentialsError("Invalid email or password.")
        
        #In case the email and password is correct, we proceed to create a token for the user
        #When calling the function exp and iat are automatically set, expiricy time is the default (60 min)
        token = create_access_token({"sub": user.id, "email": user.email})
        return token